// Structured descriptions for each number following the template:
// synthesis, calculation, gifts, challenge, example, advice

export interface NumberTemplateDesc {
  synthesis: string;
  gifts: string;
  challenge: string;
  example: string;
  advice: string;
}

type NumberType = 'destino' | 'io' | 'anima' | 'personalita' | 'quintessenza' | 'ciclo';
type Lang = 'it' | 'en';

const calculationMethods: Record<Lang, Record<NumberType, string>> = {
  it: {
    destino: "Si ricava dalla tua data di nascita: si sommano giorno, mese e anno, e si riducono a un numero solo.",
    io: "Si ricava dal tuo nome completo: ogni lettera ha un numero, si sommano tutti e si riducono a uno solo.",
    anima: "Si ricava dalle vocali del tuo nome completo: si sommano i loro valori e si riducono a un numero solo.",
    personalita: "Si ricava dalle consonanti del tuo nome completo: si sommano i loro valori e si riducono a un numero solo.",
    quintessenza: "Si ricava sommando il numero dell'Io e il numero del Destino, fino a ottenere una cifra sola (tranne 11 e 22).",
    ciclo: "I Cicli della Vita vengono dalla tua data di nascita: il primo dal mese, il secondo dal giorno, il terzo dall'anno.",
  },
  en: {
    destino: "Derived from your birth date: day, month and year are added together and reduced to a single digit.",
    io: "Derived from your full name: each letter has a number value, all are summed and reduced to a single digit.",
    anima: "Derived from the vowels of your full name: their values are summed and reduced to a single digit.",
    personalita: "Derived from the consonants of your full name: their values are summed and reduced to a single digit.",
    quintessenza: "Derived by adding the Self number and the Destiny number, reducing to a single digit (except 11 and 22).",
    ciclo: "Life Cycles come from your birth date: the first from the month, the second from the day, the third from the year.",
  },
};

export function getCalculationMethod(type: NumberType, lang: string = 'it'): string {
  const l = (lang?.substring(0, 2) === 'en' ? 'en' : 'it') as Lang;
  return calculationMethods[l][type];
}

const typeSynthesis: Record<Lang, Record<NumberType, string>> = {
  it: {
    destino: "Mostra la strada che la vita ti chiede di percorrere, passo dopo passo.",
    io: "Mostra come ti presenti al mondo e cosa sai fare meglio.",
    anima: "Mostra cosa desideri davvero nel profondo del cuore.",
    personalita: "Mostra come ti vedono gli altri dall'esterno.",
    quintessenza: "È il punto più alto del tuo potenziale: dove i tuoi talenti e la tua missione si uniscono.",
    ciclo: "Mostra che tipo di energia domina in una fase precisa della tua vita.",
  },
  en: {
    destino: "Shows the path that life asks you to walk, step by step.",
    io: "Shows how you present yourself to the world and what you do best.",
    anima: "Shows what you truly desire deep in your heart.",
    personalita: "Shows how others see you from the outside.",
    quintessenza: "It is the highest point of your potential: where your talents and your mission unite.",
    ciclo: "Shows what type of energy dominates a specific phase of your life.",
  },
};

export function getTypeSynthesis(type: NumberType, lang: string = 'it'): string {
  const l = (lang?.substring(0, 2) === 'en' ? 'en' : 'it') as Lang;
  return typeSynthesis[l][type];
}

// Template descriptions per number type per number value
const templateDescriptions: Record<Lang, Record<number, Partial<Record<NumberType, NumberTemplateDesc>>>> = {
  it: {
    1: {
      destino: {
        synthesis: "Il numero di chi fa le cose da solo, con coraggio e voglia di essere il primo.",
        gifts: "Sai prendere decisioni, non hai paura di iniziare qualcosa di nuovo, hai il coraggio di andare avanti anche quando gli altri si fermano.",
        challenge: "A volte pensi solo a te stesso e fai fatica a lavorare in squadra. Potresti voler comandare troppo, oppure non chiedere mai aiuto.",
        example: "Pensa a chi apre un'attività partendo da zero. O a chi prende una decisione importante quando tutti gli altri hanno paura. Chi cambia vita senza aspettare il permesso di nessuno.",
        advice: "Essere un leader non vuol dire comandare: vuol dire dare il buon esempio. Impara anche ad ascoltare gli altri e a lasciarti aiutare.",
      },
      io: {
        synthesis: "Ti fai notare perché sei deciso e sicuro di te. Sei uno che sa cosa vuole.",
        gifts: "Hai idee originali, sai decidere in fretta, la gente si fida di te perché trasmetti sicurezza.",
        challenge: "A volte sembri troppo duro o distante. Devi imparare a usare la tua forza senza far sentire gli altri piccoli.",
        example: "Sei quello a cui tutti chiedono consiglio nel gruppo. Quando c'è un problema, tutti guardano te.",
        advice: "Hai una voce forte: usala per dare coraggio agli altri, non per zittirli. Una parola gentile vale più di un ordine.",
      },
      anima: {
        synthesis: "Dentro di te vuoi essere libero, vero e padrone della tua vita.",
        gifts: "Hai un coraggio interiore enorme, vuoi essere autentico a tutti i costi e sai stare bene anche da solo.",
        challenge: "Il tuo bisogno di libertà può allontanare le persone. Potresti chiuderti per paura di perdere la tua indipendenza.",
        example: "Sei quello che sente un fuoco dentro che lo spinge a creare qualcosa di suo. Non riesci a fare finta di essere diverso da quello che sei.",
        advice: "Essere forti non vuol dire non aver bisogno di nessuno. Lascia entrare le persone giuste: la vera forza è anche saper chiedere aiuto.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona forte, sicura e che sa il fatto suo.",
        gifts: "Quando entri in una stanza la gente ti nota. Dai l'impressione di sapere sempre cosa fare.",
        challenge: "A volte sembri troppo freddo o difficile da avvicinare. La gente potrebbe avere paura di parlarti.",
        example: "Sei quello che quando entra in una stanza attira gli sguardi senza fare niente. Ti scelgono sempre come capo nei gruppi.",
        advice: "Ogni tanto fai vedere anche il tuo lato dolce. La gente si affeziona a chi è vero, non a chi sembra perfetto.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando prendi l'iniziativa e crei qualcosa dal nulla.",
        gifts: "Sai unire quello che sei con quello che fai e trasformarlo in azione. Hai la stoffa del pioniere.",
        challenge: "Fare troppo senza mai fermarti ti può esaurire. Impara quando è il momento di fare una pausa.",
        example: "Sei come l'inventore che ha un'idea geniale e la trasforma in realtà. Riesci a unire il cuore con l'azione.",
        advice: "Il tuo dono più grande è iniziare. Non aspettare che tutto sia perfetto: il primo passo è quello che conta di più.",
      },
    },
    2: {
      destino: {
        synthesis: "Il numero di chi sa stare con gli altri, ascoltare e creare pace.",
        gifts: "Capisci come si sentono le persone, sai mettere d'accordo tutti, ascolti davvero e sai far sentire gli altri importanti.",
        challenge: "A volte ti perdi nell'aiutare gli altri e ti dimentichi di te. Potresti aver paura dei litigi e non dire mai quello che pensi.",
        example: "Pensa a chi riesce a far fare pace a due amici che litigano. O a chi capisce come stai solo guardandoti in faccia.",
        advice: "Essere sensibili è un superpotere, non una debolezza. Ma ricordati anche di dire quello che vuoi tu: puoi voler bene senza perdere te stesso.",
      },
      io: {
        synthesis: "Ti esprimi con gentilezza e sai creare un ambiente dove tutti si sentono bene.",
        gifts: "Sai mettere d'accordo le persone, parli con delicatezza e riesci a creare legami veri tra la gente.",
        challenge: "A volte sembri troppo gentile e la gente potrebbe pensare che non hai opinioni tue. Devi imparare a dire la tua anche quando è scomodo.",
        example: "Sei quello che riesce a far lavorare insieme persone molto diverse. Con una parola dolce risolvi problemi che sembravano impossibili.",
        advice: "Essere gentili non vuol dire essere deboli. Dire quello che pensi con rispetto è il modo più bello di voler bene.",
      },
      anima: {
        synthesis: "Dentro di te vuoi pace, relazioni vere e sentirti al sicuro con le persone che ami.",
        gifts: "Senti le cose prima degli altri, sai creare legami profondi e hai bisogno di bellezza e armonia intorno a te.",
        challenge: "Per non litigare, a volte tieni tutto dentro e accumuli rabbia. Potresti mettere sempre gli altri prima di te.",
        example: "Sei quello che sente il dolore degli altri come se fosse il suo. Crei posti dove tutti si sentono a casa.",
        advice: "La pace vera non è evitare i problemi, ma affrontarli restando calmi. Impara a dire quello che senti.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona dolce, su cui si può contare e che mette a proprio agio.",
        gifts: "Quando sei presente, la gente si rilassa. Dai l'idea di essere una persona calma e affidabile.",
        challenge: "A volte sembri troppo buono e qualcuno potrebbe approfittarsene. Devi imparare a dire di no.",
        example: "Sei quello a cui tutti raccontano i segreti. Ti cercano quando stanno male perché sanno che li ascolterai.",
        advice: "Fai vedere anche la tua forza. Chi ti vuole bene davvero rispetta anche i tuoi no.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando unisci le persone e crei armonia intorno a te.",
        gifts: "Sai costruire ponti tra persone diverse e trasformare le differenze in ricchezza.",
        challenge: "A forza di aiutare tutti, rischi di dimenticarti di te. Trovare il tuo equilibrio è la lezione più importante.",
        example: "Sei come chi crea un gruppo dove persone diverse si capiscono e collaborano. Fai da collante.",
        advice: "Sei la colla che tiene insieme le cose. Ma ricorda: anche la colla ha bisogno di cura.",
      },
    },
    3: {
      destino: {
        synthesis: "Il numero di chi sa comunicare, creare e portare gioia nella vita degli altri.",
        gifts: "Hai un entusiasmo che contagia tutti, sai parlare bene, hai talento per l'arte e la creatività, e fai amicizia facilmente.",
        challenge: "Rischi di iniziare mille cose senza finirne nessuna. A volte usi le battute per non affrontare i problemi seri.",
        example: "Pensa all'artista che riesce a far emozionare la gente con le sue opere. O a chi sa spiegare le cose difficili in modo semplice e divertente.",
        advice: "La tua creatività è come un fiume: se non gli dai una direzione, si disperde. Scegli una cosa e dedicati con tutto te stesso: i risultati ti sorprenderanno.",
      },
      io: {
        synthesis: "Ti esprimi con vivacità e carisma. La gente ti ascolta volentieri perché sai comunicare.",
        gifts: "Sai raccontare, intrattenere e far ridere. Hai una creatività naturale e la gente è attratta dalla tua energia.",
        challenge: "A volte sembri poco serio o dispersivo. Devi imparare a dare sostanza a quello che dici.",
        example: "Sei quello che cattura l'attenzione di tutti con una storia. Trasformi ogni discorso in qualcosa di interessante.",
        advice: "Le parole hanno un potere enorme: usale per far crescere gli altri, non solo per far divertire.",
      },
      anima: {
        synthesis: "Dentro di te vuoi esprimerti, essere unico e goderti la bellezza della vita.",
        gifts: "Hai una creatività interiore naturale, sei ottimista, ami le cose belle e sai trovare la gioia nelle piccole cose.",
        challenge: "Il bisogno che gli altri ti apprezzino può portarti a nascondere quello che senti veramente. A volte usi la leggerezza per scappare dal dolore.",
        example: "Sei quello che si sente davvero vivo solo quando crea qualcosa. Trovi poesia anche nelle cose più semplici.",
        advice: "Non devi sempre essere il sole della festa. Anche la pioggia serve per far crescere i fiori: lascia che anche le emozioni difficili ti attraversino.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona solare, simpatica e piena di vita.",
        gifts: "Porti il buon umore ovunque vai. Hai il dono di alleggerire le situazioni pesanti e di far sorridere.",
        challenge: "A volte sembri poco serio e la gente potrebbe non prendere sul serio la tua profondità.",
        example: "Sei quello che viene invitato a tutte le feste perché sa creare l'atmosfera giusta. Porti luce ovunque arrivi.",
        advice: "Fai vedere anche il tuo lato profondo. Le amicizie più belle nascono quando ti mostri per quello che sei davvero.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando comunichi in modo creativo e porti gioia alle persone.",
        gifts: "Sai trasformare le idee in qualcosa che tocca il cuore della gente. La tua creatività ha un messaggio forte.",
        challenge: "Avere troppe idee e poca disciplina può bloccarti. Devi scegliere su cosa concentrarti.",
        example: "Sei come l'artista che riesce a cambiare il modo in cui le persone vedono le cose, usando la bellezza e le parole.",
        advice: "Hai il dono di far brillare le cose. Scegli cosa illuminare e dedicaci tutta la tua energia.",
      },
    },
    4: {
      destino: {
        synthesis: "Il numero di chi costruisce cose solide, con pazienza e metodo.",
        gifts: "Sei affidabile, costante e concreto. Sai costruire cose che durano nel tempo, passo dopo passo.",
        challenge: "A volte sei troppo rigido e hai paura dei cambiamenti. Ti attacchi alle abitudini e fai fatica ad accettare le novità.",
        example: "Pensa a chi costruisce una casa mattone dopo mattone. O al genitore che crea un ambiente sicuro per i figli. Chi costruisce un'azienda con pazienza e costanza.",
        advice: "Le fondamenta migliori sono quelle che sanno piegarsi. Un albero resiste alla tempesta perché è flessibile, non perché è rigido.",
      },
      io: {
        synthesis: "Ti esprimi con ordine, precisione e sai organizzare le cose come nessun altro.",
        gifts: "Sei affidabile, sai pianificare, curi i dettagli e ti esprimi in modo chiaro e concreto.",
        challenge: "A volte sembri troppo rigido o prevedibile. Devi dare spazio anche alla parte spontanea di te.",
        example: "Sei quello che trasforma il caos in ordine senza fatica. Tutti ti cercano quando serve un piano preciso.",
        advice: "L'ordine è il tuo superpotere, ma ogni tanto lasciati sorprendere dalla vita. Anche l'imprevisto può essere bello.",
      },
      anima: {
        synthesis: "Dentro di te vuoi sicurezza, stabilità e che ogni cosa sia al suo posto.",
        gifts: "Hai una costanza interiore rara, un forte senso del dovere e la pazienza di costruire le cose con calma.",
        challenge: "Il bisogno di controllare tutto può bloccarti. Potresti resistere ai cambiamenti per paura di quello che non conosci.",
        example: "Sei quello che trova pace quando il lavoro è fatto bene. Ti senti a casa quando tutto è in ordine.",
        advice: "La vera sicurezza non viene dalle cose esterne. Impara a sentirti stabile anche quando tutto cambia: è lì che cresci davvero.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona solida, seria e con i piedi per terra.",
        gifts: "Dai un senso di stabilità a chi ti sta intorno. La gente si fida di te perché sembri sempre preparato.",
        challenge: "A volte sembri noioso o troppo serio. La gente potrebbe non vedere il tuo lato creativo e divertente.",
        example: "Sei quello a cui tutti affidano le cose importanti. Ti scelgono sempre per i compiti più delicati.",
        advice: "Ogni tanto sorprendi la gente. Mostra il tuo lato giocoso: ti apprezzeranno ancora di più.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando costruisci qualcosa di importante che dura nel tempo.",
        gifts: "Sai dare una forma concreta alle idee e trasformare i sogni in cose reali e solide.",
        challenge: "Voler fare tutto perfetto può bloccarti. Non aspettare che sia tutto a posto per partire.",
        example: "Sei come chi costruisce cose che restano nel tempo e che servono a tante persone.",
        advice: "Costruisci con amore, non solo con metodo. Le cose che durano di più sono quelle in cui metti il cuore.",
      },
    },
    5: {
      destino: {
        synthesis: "Il numero di chi ama il cambiamento, la libertà e vivere tante esperienze diverse.",
        gifts: "Ti adatti a tutto, sei curioso, versatile, hai il coraggio di esplorare e sai reinventarti quando serve.",
        challenge: "Rischi di essere instabile e di esagerare. Potresti scappare dalle responsabilità inseguendo sempre qualcosa di nuovo.",
        example: "Pensa a chi impara più viaggiando che stando sui libri. O a chi cambia lavoro per seguire la sua passione. Chi trasforma ogni problema in un'opportunità.",
        advice: "La vera libertà non è scappare, ma scegliere con coscienza dove restare. Trova la tua stabilità anche nel movimento.",
      },
      io: {
        synthesis: "Ti esprimi con energia, sei sempre in movimento e ti attira tutto ciò che è nuovo.",
        gifts: "Ti adatti facilmente, comunichi con vivacità, sai cogliere le occasioni al volo e hai un'energia contagiosa.",
        challenge: "A volte sembri incostante o poco affidabile. Devi imparare a finire quello che inizi.",
        example: "Sei quello che si sente a casa ovunque. Trasformi ogni esperienza in una storia avvincente.",
        advice: "Si può andare in profondità anche restando fermi. Non tutto quello che luccica è oro: scegli con attenzione.",
      },
      anima: {
        synthesis: "Dentro di te vuoi libertà, avventura e la possibilità di provare tutto nella vita.",
        gifts: "Hai uno spirito libero, una gran sete di esperienze, la mente aperta e ti entusiasmi per le novità.",
        challenge: "Il tuo bisogno di libertà può impedirti di impegnarti davvero. Potresti scappare proprio quando le cose diventano serie.",
        example: "Sei quello che si sente soffocare dalla routine. Hai bisogno di sentire l'aria fresca in faccia per sentirti vivo.",
        advice: "L'avventura più grande è conoscerti. Non devi andare lontano per trovare quello che cerchi.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona energica, affascinante e piena di sorprese.",
        gifts: "Hai un fascino naturale, dai l'idea di libertà e avventura, e attrai la gente con la tua freschezza.",
        challenge: "A volte sembri superficiale o sfuggente. La gente potrebbe fare fatica a fidarsi della tua costanza.",
        example: "Sei quello che tutti vorrebbero come compagno di viaggio. Porti una ventata di novità ovunque arrivi.",
        advice: "Sii affascinante ma anche affidabile. La gente ha bisogno di sapere che può contare su di te.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando porti cambiamenti positivi e rinnovi le cose.",
        gifts: "Sai portare aria nuova dove serve e vedi possibilità dove gli altri vedono muri.",
        challenge: "L'irrequietezza può rovinare quello che costruisci. Impara a restare abbastanza per raccogliere i frutti.",
        example: "Sei come chi riesce a cambiare un intero ambiente con la sua energia e la sua voglia di novità.",
        advice: "Il cambiamento più forte è quello che nasce dalla consapevolezza, non dalla fuga.",
      },
    },
    6: {
      destino: {
        synthesis: "Il numero di chi si prende cura degli altri, ama la famiglia e cerca armonia in tutto.",
        gifts: "Sai proteggere e curare chi ami, crei bellezza e armonia intorno a te, hai un grande senso di responsabilità e un occhio per le cose belle.",
        challenge: "Rischi di sacrificarti troppo per gli altri e di confondere l'amore con il controllo. Potresti sentirti in colpa se non riesci ad aiutare tutti.",
        example: "Pensa al genitore che crea un ambiente sicuro senza soffocare. O a chi dedica la vita a rendere il mondo un posto più bello e giusto.",
        advice: "Non puoi dare acqua agli altri se il tuo bicchiere è vuoto. Prenditi cura di te con la stessa attenzione che dedichi agli altri.",
      },
      io: {
        synthesis: "Ti esprimi con calore e sai far sentire le persone amate e protette.",
        gifts: "Sai creare armonia, hai talento artistico, ti esprimi con amore e hai un bel senso estetico.",
        challenge: "A volte sembri troppo appiccicoso o protettivo. Devi imparare ad amare senza controllare.",
        example: "Sei quello che trasforma ogni posto in un luogo accogliente. Con la tua presenza fai sentire tutti importanti.",
        advice: "L'amore più grande è quello che lascia liberi. Vuoi bene senza togliere libertà a chi ami.",
      },
      anima: {
        synthesis: "Dentro di te vuoi amore, bellezza e la possibilità di prenderti cura di chi ti sta intorno.",
        gifts: "Sai amare senza condizioni, hai un senso della bellezza naturale, crei armonia e ti dedichi con tutto il cuore.",
        challenge: "Il bisogno di sentirti necessario può creare dipendenza. Potresti confondere il sacrificio con l'amore.",
        example: "Sei quello che vuole rendere bello ogni dettaglio. Ti illumini quando puoi prenderti cura di qualcuno.",
        advice: "Vuoi bene a te stesso come vuoi bene agli altri. La bellezza che cerchi fuori è già dentro di te.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona calda, responsabile e con buon gusto.",
        gifts: "Quando ci sei tu, la gente si sente al sicuro. Dai l'idea di essere affidabile e premuroso.",
        challenge: "A volte sembri troppo protettivo. La gente potrebbe sentirsi soffocata dalle tue attenzioni.",
        example: "Sei quello che organizza tutto per far stare bene gli altri. Ti scelgono sempre come confidente.",
        advice: "Lascia che gli altri facciano i propri errori. Si cresce attraverso l'esperienza, non attraverso la protezione.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando ami con consapevolezza e crei bellezza intorno a te.",
        gifts: "Sai trasformare gli ambienti e le relazioni grazie al tuo amore e alla tua cura.",
        challenge: "Volere tutto perfetto nelle relazioni può impedirti di accettare le imperfezioni della vita.",
        example: "Sei come chi crea una comunità dove le persone si sentono amate e rispettate.",
        advice: "La perfezione non esiste, ma la bellezza sì. La trovi proprio nelle imperfezioni: è lì che sta la magia.",
      },
    },
    7: {
      destino: {
        synthesis: "Il numero di chi pensa in profondità, cerca risposte e vuole capire il senso delle cose.",
        gifts: "Sai analizzare, pensi in modo profondo, hai una grande intuizione e cerchi sempre la verità.",
        challenge: "Rischi di isolarti dal mondo e chiuderti nella tua testa. Potresti diventare diffidente e fare fatica a fidarti degli altri.",
        example: "Pensa al ricercatore che dedica la vita a capire come funzionano le cose. O al filosofo che fa domande che nessuno si pone. Chi trova risposte dove gli altri non cercano.",
        advice: "La cosa più bella che puoi fare con quello che sai è condividerlo. Non aver paura di aprirti: la saggezza cresce quando la regali.",
      },
      io: {
        synthesis: "Ti esprimi con poche parole ma piene di significato. Vai sempre al cuore delle cose.",
        gifts: "Pensi in modo profondo, vai oltre le apparenze, e quando parli dici cose che contano davvero.",
        challenge: "A volte sembri distante o superiore. Devi imparare a spiegare le tue idee in modo semplice e accessibile.",
        example: "Sei quello che con due parole centra il punto. Tutti ti chiedono un parere perché vedono le cose in modo diverso da te.",
        advice: "Non tutto si capisce con la testa. Ogni tanto lascia spazio al cuore e alla pancia.",
      },
      anima: {
        synthesis: "Dentro di te vuoi capire, cercare la verità e avere momenti di pace e silenzio.",
        gifts: "Hai un'intuizione profonda, cerchi sempre un significato, sai stare in silenzio e hai una ricerca interiore naturale.",
        challenge: "Il bisogno di stare solo può diventare isolamento. Potresti usare la testa come scudo per non sentire le emozioni.",
        example: "Sei quello che ha bisogno di silenzio per ricaricarsi. Trovi pace quando puoi pensare e riflettere in tranquillità.",
        advice: "La verità che cerchi non è solo nei libri. A volte la risposta arriva quando smetti di cercarla e ti lasci andare.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona misteriosa, intelligente e che sa molte cose.",
        gifts: "Hai un'aria interessante, la gente ti rispetta e vorrebbe sapere cosa pensi davvero.",
        challenge: "A volte sembri freddo o impossibile da avvicinare. La gente potrebbe sentirsi a disagio con te.",
        example: "Sei quello di cui tutti vorrebbero conoscere i pensieri. Attrai le persone per la tua profondità e il tuo mistero.",
        advice: "Lasciati conoscere. Le persone che meritano il tuo tempo apprezzeranno la tua verità più del tuo mistero.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando cerchi la verità e la condividi con gli altri.",
        gifts: "Sai andare a fondo nelle cose e trasformare quello che impari in consigli utili per tutti.",
        challenge: "Pensare troppo può bloccarti. A volte bisogna agire prima di aver capito tutto.",
        example: "Sei come il maestro che trasforma la sua ricerca in insegnamenti semplici che cambiano la vita della gente.",
        advice: "La saggezza più grande è sapere che non sai tutto. Resta curioso e umile: la verità si mostra a chi è aperto.",
      },
    },
    8: {
      destino: {
        synthesis: "Il numero di chi sa gestire il potere, i soldi e le risorse con forza e visione.",
        gifts: "Sai guidare le persone, hai fiuto per gli affari, sei determinato e hai una visione chiara di dove vuoi arrivare.",
        challenge: "Rischi di pensare solo ai soldi e al successo, diventando duro con gli altri. Potresti usare il potere per controllare invece che per aiutare.",
        example: "Pensa a chi costruisce un'azienda di successo con onestà. O a chi usa le proprie risorse per fare del bene alla comunità. Chi crea ricchezza per sé e per gli altri.",
        advice: "Il vero potere non è quello che usi sugli altri, ma quello che usi su te stesso. Usa quello che hai con onestà e il successo durerà per sempre.",
      },
      io: {
        synthesis: "Ti esprimi con autorità e ambizione. Sai gestire persone e situazioni con sicurezza.",
        gifts: "Hai una visione chiara, sai organizzare, trasmetti forza e competenza, e hai un talento naturale per gestire le cose.",
        challenge: "A volte sembri troppo ambizioso o calcolatore. Devi far vedere anche il tuo lato umano e gentile.",
        example: "Sei quello che trasforma ogni situazione in un'opportunità. Vedi il potenziale dove gli altri vedono problemi.",
        advice: "Il successo senza un significato è vuoto. Chiediti sempre: per chi e per cosa sto lavorando?",
      },
      anima: {
        synthesis: "Dentro di te vuoi abbondanza, riconoscimento e lasciare un segno nel mondo.",
        gifts: "Hai un'ambizione sana, un forte senso di giustizia, vuoi fare cose eccellenti e hai una forza interiore enorme.",
        challenge: "Il bisogno di successo può renderti dipendente dal giudizio degli altri. Potresti confondere il tuo valore con i tuoi risultati.",
        example: "Sei quello che sente di essere nato per fare qualcosa di grande. Non ti accontenti mai della mediocrità.",
        advice: "Tu non sei i tuoi risultati. Il tuo valore non dipende da quello che possiedi o raggiungi. Vali per quello che sei.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona potente, ambiziosa e capace di grandi cose.",
        gifts: "Hai una presenza forte, dai l'idea di successo e competenza, e la gente si fida delle tue capacità.",
        challenge: "A volte fai un po' paura. La gente potrebbe temere di non essere all'altezza delle tue aspettative.",
        example: "Sei quello che tutti vorrebbero come socio. Trasmetti un'energia di determinazione e successo.",
        advice: "Fai vedere anche la tua generosità. Le persone più forti sono quelle che usano il loro potere per aiutare gli altri.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando crei abbondanza in modo onesto e generoso.",
        gifts: "Sai trasformare le idee in cose concrete e creare ricchezza che fa del bene a tutti.",
        challenge: "La tentazione di usare il potere solo per te stesso è la tua prova più grande. Devi trovare l'equilibrio tra avere e dare.",
        example: "Sei come chi costruisce aziende che creano valore per le persone, non solo profitto.",
        advice: "Il potere più grande è quello di fare del bene su larga scala. Usa le tue capacità per servire, non solo per accumulare.",
      },
    },
    9: {
      destino: {
        synthesis: "Il numero di chi ha un cuore grande, capisce il dolore degli altri e vuole lasciare il mondo un posto migliore.",
        gifts: "Sai perdonare, vedi le cose dall'alto, hai una saggezza che viene dall'esperienza e dai senza aspettarti niente in cambio.",
        challenge: "Rischi di caricarti i problemi di tutti sulle spalle. Potresti farti vittima o sprecare le tue energie cercando di aggiustare tutto senza curarti di te.",
        example: "Pensa al dottore che va a curare le persone in zone di guerra. O al nonno che insegna ai nipoti valori che durano per sempre. Chi perdona anche quando è difficile, perché capisce che siamo tutti fragili.",
        advice: "Non puoi salvare il mondo se prima non stai bene tu. Impara a lasciar andare le cose che non puoi cambiare: la vera saggezza è sapere cosa vale la pena tenere.",
      },
      io: {
        synthesis: "Ti esprimi con umanità e generosità. Hai una vocazione naturale ad aiutare gli altri.",
        gifts: "Vedi il quadro grande, sai ispirare compassione, e hai il talento di far sentire le persone capite e accolte.",
        challenge: "A volte sembri distaccato o troppo idealista. Devi restare con i piedi per terra anche quando sogni in grande.",
        example: "Sei quello che tocca il cuore delle persone con le parole e con i fatti. Ispiri gli altri a diventare persone migliori.",
        advice: "Non devi essere perfetto per fare la differenza. Anche un piccolo gesto di gentilezza può cambiare la giornata di qualcuno.",
      },
      anima: {
        synthesis: "Dentro di te vuoi fare qualcosa di buono per il mondo e aiutare l'umanità a crescere.",
        gifts: "Hai una compassione profonda, una saggezza dell'anima, sai perdonare e ami le persone in modo universale.",
        challenge: "Il bisogno di salvare gli altri può farti dimenticare te stesso. Potresti sentirti responsabile del dolore di tutti.",
        example: "Sei quello che sente un legame profondo con tutta l'umanità. Piangi per le ingiustizie anche quando non ti riguardano.",
        advice: "Aiutare non vuol dire sacrificarsi. Fai più bene al mondo quando sei in equilibrio e stai bene tu per primo.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona saggia, dal cuore grande e che capisce tutti.",
        gifts: "Hai una presenza calda, la gente si sente accolta da te, e dai l'idea di essere una persona profonda e comprensiva.",
        challenge: "A volte sembri troppo lontano o in un altro mondo. La gente potrebbe vederti come irraggiungibile.",
        example: "Sei quello che tutti rispettano per la sua onestà. Ti cercano perché sai capire senza giudicare.",
        advice: "Sii presente nella vita di tutti i giorni, non solo nelle grandi idee. La gente ha bisogno della tua umanità, non della tua perfezione.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando aiuti gli altri con consapevolezza e trasformi il dolore in saggezza.",
        gifts: "Sai trovare il significato profondo in ogni esperienza e guidare gli altri nei momenti di cambiamento.",
        challenge: "Il rischio è di sognare in grande senza fare niente di concreto. La saggezza senza azione non serve a nessuno.",
        example: "Sei come il maestro che ha attraversato le difficoltà della vita e ne ha tirato fuori lezioni che condivide con tutti.",
        advice: "La tua saggezza è il tuo dono più prezioso. Non tenerla per te: il mondo ha bisogno della tua luce.",
      },
    },
    11: {
      destino: {
        synthesis: "Il numero maestro di chi ha una visione speciale, un'intuizione fuori dal comune e una sensibilità molto forte.",
        gifts: "Hai un sesto senso fortissimo, sai ispirare gli altri, sei molto sensibile e vedi cose che le altre persone non vedono.",
        challenge: "Vivi una tensione tra il mondo pratico e quello interiore. Puoi soffrire di ansia, sentirti troppo sensibile e pensare di non essere all'altezza della tua missione.",
        example: "Pensa a chi vede le cose prima degli altri e sa dove andrà il futuro. O all'artista che crea opere che sembrano venire da un altro mondo. A chi risveglia la coscienza delle persone.",
        advice: "Non devi portare questo peso da solo. Il tuo dono è come un canale: fai passare la luce, non la trattenere. Tieni i piedi per terra mentre guardi il cielo: la tua visione ha bisogno di basi solide.",
      },
      io: {
        synthesis: "Ti esprimi come una fonte di ispirazione, con una sensibilità e un'intuizione speciali.",
        gifts: "Sai ispirare le persone in profondità, la tua intuizione guida tutto quello che fai, e hai una sensibilità artistica fuori dal comune.",
        challenge: "Essere così sensibile può farti soffrire. La sfida è esprimere la tua visione senza farti travolgere.",
        example: "Sei quello che con le parole o i gesti tocca corde profonde nella gente. Il tuo lavoro sembra venire da una fonte speciale.",
        advice: "Sei un faro: la tua luce guida gli altri. Ma ricordati di riposare e di prenderti cura della tua fiamma.",
      },
      anima: {
        synthesis: "Dentro di te sei guidato da una visione più grande e dal bisogno di illuminare il cammino degli altri.",
        gifts: "Hai un'intuizione quasi magica, una sensibilità rara, un legame con qualcosa di più grande e la capacità di sentire cose invisibili.",
        challenge: "La tua sensibilità estrema può renderti fragile davanti all'energia degli altri. Potresti sentirti un pesce fuor d'acqua in questo mondo.",
        example: "Sei quello che percepisce cose che gli altri non vedono. Hai sogni che si avverano o intuizioni che si rivelano sempre giuste.",
        advice: "Il tuo dono è reale, non sei strano. Impara a proteggere la tua energia e a scegliere con chi condividere quello che vedi.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona speciale, intensa e con una luce particolare.",
        gifts: "Hai una presenza magnetica, ispiri le persone e dai l'idea di avere una profondità e una sensibilità uniche.",
        challenge: "A volte sembri troppo intenso o diverso. La gente potrebbe non capire la tua profondità.",
        example: "Sei quello che quando entra in una stanza cambia l'atmosfera. Ispiri gli altri semplicemente con la tua presenza.",
        advice: "Non tutti capiranno la tua luce, e va bene così. Circondati di persone che vedono il tuo valore.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando illumini gli altri con la tua visione e la tua intuizione.",
        gifts: "Sai trasformare l'ispirazione in qualcosa di concreto e utile, e hai il talento di risvegliare il potenziale nascosto delle persone.",
        challenge: "La tensione tra quello che vedi e la realtà può stancarti. Trova il modo di portare le tue intuizioni nel mondo reale.",
        example: "Sei come il maestro-visionario che trasforma le sue intuizioni in insegnamenti semplici che cambiano la vita della gente.",
        advice: "La tua visione è un dono per il mondo. Non lasciarla morire nell'indecisione: agisci con coraggio.",
      },
    },
    22: {
      destino: {
        synthesis: "Il numero maestro del grande costruttore: chi è capace di realizzare progetti enormi che durano nel tempo.",
        gifts: "Hai una visione grandiosa, sai trasformare le grandi idee in cose concrete, sei un leader che trasforma, e sai unire i sogni con la pratica.",
        challenge: "Senti una pressione enorme, sia da te stesso che dagli altri. Potresti crollare sotto il peso delle aspettative o vivere in piccolo per paura della tua stessa grandezza.",
        example: "Pensa a chi fonda un'organizzazione che cambia le regole del gioco. O a chi crea sistemi che migliorano la vita di tantissime persone. Chi costruisce ponti tra l'impossibile e il possibile.",
        advice: "Sei nato per costruire qualcosa di grande, ma non devi farlo tutto in una volta. Ogni cattedrale è stata costruita una pietra alla volta. Inizia, e il progetto prenderà forma da solo.",
      },
      io: {
        synthesis: "Ti esprimi come un costruttore di visioni: sai trasformare l'impossibile in realtà.",
        gifts: "Vedi il progetto completo nella tua mente e lo realizzi passo dopo passo. Unisci il sogno con la pratica.",
        challenge: "La grandezza della tua visione può paralizzarti. La sfida è iniziare anche quando il traguardo sembra impossibile.",
        example: "Sei quello che riesce a presentare un'idea enorme in modo così concreto che tutti vogliono farne parte.",
        advice: "Non sottovalutare il potere del primo passo. Ogni grande opera inizia con un singolo gesto di coraggio.",
      },
      anima: {
        synthesis: "Dentro di te vuoi lasciare qualcosa di concreto che duri più a lungo di te.",
        gifts: "Pensi a lungo termine, sai pensare in grande e hai la determinazione di costruire qualcosa che serve al bene di tutti.",
        challenge: "Il peso della tua missione può schiacciarti. Potresti sentirti non all'altezza di quello che sei chiamato a fare.",
        example: "Sei quello che sente di avere una missione più grande di sé. Non riesci ad accontentarti di una vita normale.",
        advice: "Non devi essere perfetto per iniziare. Il mondo ha bisogno delle tue costruzioni imperfette più della tua perfezione ferma.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona visionaria ma concreta, capace di cose grandi.",
        gifts: "Hai una presenza autorevole, dai l'idea di essere competente e visionario, e la gente si fida dei tuoi grandi progetti.",
        challenge: "A volte sembri troppo ambizioso o distante. La gente potrebbe sentirsi piccola davanti a te.",
        example: "Sei quello che quando parla di un progetto fa credere a tutti che sia possibile. Ispiri fiducia anche nelle imprese più difficili.",
        advice: "Coinvolgi gli altri nella tua visione. I grandi costruttori non costruiscono da soli: sanno ispirare e far lavorare tutti insieme.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando realizzi cose concrete che servono a tante persone.",
        gifts: "Hai un talento unico nel trasformare i sogni in cose reali, e sai costruire cose che durano per le generazioni future.",
        challenge: "La perfezione è nemica del bene. Non aspettare le condizioni ideali: costruisci con quello che hai.",
        example: "Sei come chi crea organizzazioni, sistemi o opere che cambiano le regole del gioco per chi verrà dopo.",
        advice: "Sei il ponte tra il cielo e la terra. La tua missione è rendere concreto quello che gli altri possono solo sognare.",
      },
    },
    33: {
      destino: {
        synthesis: "Il numero maestro dell'amore per tutti: una guida amorevole che dedica la vita agli altri.",
        gifts: "Ami senza condizioni, sai curare le ferite degli altri, guidi con dolcezza, ti dedichi al servizio e ispiri le persone a livello profondo.",
        challenge: "Rischi di sacrificarti completamente per gli altri, dimenticando che anche tu hai bisogno di essere curato. Potresti annullarti nel tentativo di aiutare tutti.",
        example: "Pensa al maestro che dedica la vita a far crescere gli altri. O a chi rinuncia ai propri interessi per un bene più grande. Alla persona che diventa un punto di riferimento per un'intera comunità.",
        advice: "L'amore per tutti inizia dall'amore per te stesso. Non puoi illuminare il mondo se la tua luce si è spenta. Prenditi cura di te con la stessa dolcezza che dai agli altri.",
      },
      io: {
        synthesis: "Ti esprimi come una guida amorevole che sa ispirare cambiamento attraverso la gentilezza.",
        gifts: "Sai curare con la tua sola presenza, esprimi un amore che va oltre il personale, e guidi le persone con dolcezza.",
        challenge: "Sacrificarti troppo può consumarti. La sfida è servire gli altri senza annullarti.",
        example: "Sei quello che con la sola presenza porta pace e guarigione. Il tuo amore trasforma chi ti sta intorno.",
        advice: "Aiuta con gioia, non con sacrificio. L'amore dato per obbligo non è amore, è una catena.",
      },
      anima: {
        synthesis: "Dentro di te vuoi amare e servire le persone con tutto quello che hai.",
        gifts: "Hai un amore immenso, una compassione senza limiti, e la capacità di vedere il bello in ogni persona.",
        challenge: "Potresti annullarti completamente per gli altri. Il confine tra dedizione e sacrificio è sottile.",
        example: "Sei quello che sente il dolore del mondo come se fosse suo. Non riesci a voltare le spalle a nessuno.",
        advice: "Anche i grandi maestri hanno bisogno di riposare. Il tuo amore è più forte quando nasce da un cuore pieno, non vuoto.",
      },
      personalita: {
        synthesis: "La gente ti vede come una persona luminosa, piena d'amore e che ispira tutti.",
        gifts: "La tua presenza cura, dai l'idea di essere saggio e pieno di compassione, e fai sentire tutti amati.",
        challenge: "A volte sembri troppo buono o ingenuo. Qualcuno potrebbe approfittare della tua generosità.",
        example: "Sei quello la cui presenza porta pace in ogni stanza. Ispiri gli altri a diventare più gentili.",
        advice: "La tua bontà non è debolezza. Ma impara a riconoscere chi merita davvero la tua energia.",
      },
      quintessenza: {
        synthesis: "Dai il meglio di te quando il tuo amore trasforma le cose e guidi gli altri con il cuore.",
        gifts: "Sai trasformare la sofferenza in saggezza e l'amore in una forza che cura tutti.",
        challenge: "Il peso di voler aiutare tutti può schiacciarti. Non sei responsabile della salvezza di ogni persona.",
        example: "Sei come il maestro-guaritore che con la propria vita diventa esempio di amore senza condizioni.",
        advice: "Sei una luce nel mondo. Ma anche la luce ha bisogno di essere alimentata. Prenditi cura della tua fiamma.",
      },
    },
  },
  en: {
    1: {
      destino: {
        synthesis: "The number of those who do things on their own, with courage and a desire to be first.",
        gifts: "You know how to make decisions, you're not afraid to start something new, and you have the courage to keep going even when others stop.",
        challenge: "Sometimes you think only of yourself and struggle to work as a team. You might want to control too much, or never ask for help.",
        example: "Think of someone who starts a business from scratch. Or someone who makes an important decision when everyone else is afraid. Someone who changes their life without waiting for anyone's permission.",
        advice: "Being a leader doesn't mean giving orders: it means setting a good example. Learn to listen to others and let yourself be helped.",
      },
      io: {
        synthesis: "You stand out because you're decisive and self-assured. You know what you want.",
        gifts: "You have original ideas, you decide quickly, and people trust you because you project confidence.",
        challenge: "Sometimes you seem too tough or distant. You need to learn to use your strength without making others feel small.",
        example: "You're the one everyone asks for advice. When there's a problem, everyone looks at you.",
        advice: "You have a strong voice: use it to encourage others, not to silence them. A kind word is worth more than an order.",
      },
      anima: {
        synthesis: "Deep down, you want to be free, authentic, and master of your own life.",
        gifts: "You have enormous inner courage, you want to be authentic at all costs, and you're comfortable being alone.",
        challenge: "Your need for freedom can push people away. You might close yourself off for fear of losing your independence.",
        example: "You're the one who feels a fire inside pushing you to create something of your own. You can't pretend to be someone you're not.",
        advice: "Being strong doesn't mean not needing anyone. Let the right people in: true strength also means knowing how to ask for help.",
      },
      personalita: {
        synthesis: "People see you as a strong, confident person who knows what they're doing.",
        gifts: "When you enter a room, people notice. You give the impression of always knowing what to do.",
        challenge: "Sometimes you seem too cold or hard to approach. People might be afraid to talk to you.",
        example: "You're the one who draws attention just by walking into a room. You're always chosen as the leader in groups.",
        advice: "Show your softer side once in a while. People grow fond of those who are real, not those who seem perfect.",
      },
      quintessenza: {
        synthesis: "You're at your best when you take the initiative and create something from nothing.",
        gifts: "You know how to unite who you are with what you do and turn it into action. You have the makings of a pioneer.",
        challenge: "Doing too much without ever stopping can drain you. Learn when it's time to take a break.",
        example: "You're like the inventor with a brilliant idea who turns it into reality. You can unite heart and action.",
        advice: "Your greatest gift is starting. Don't wait for everything to be perfect: the first step is the one that matters most.",
      },
    },
    2: {
      destino: {
        synthesis: "The number of those who know how to be with others, listen, and create peace.",
        gifts: "You understand how people feel, you can bring everyone together, you truly listen, and you make others feel important.",
        challenge: "Sometimes you lose yourself helping others and forget about yourself. You might fear conflict and never say what you think.",
        example: "Think of someone who can make two arguing friends reconcile. Or someone who knows how you feel just by looking at your face.",
        advice: "Being sensitive is a superpower, not a weakness. But remember to also say what you want: you can love without losing yourself.",
      },
      io: {
        synthesis: "You express yourself with kindness and create an environment where everyone feels at ease.",
        gifts: "You bring people together, speak with gentleness, and create genuine bonds between people.",
        challenge: "Sometimes you seem too kind and people might think you have no opinions. You need to speak up even when it's uncomfortable.",
        example: "You're the one who gets very different people to work together. With a gentle word, you solve problems that seemed impossible.",
        advice: "Being kind doesn't mean being weak. Saying what you think with respect is the most beautiful way to show love.",
      },
      anima: {
        synthesis: "Deep down, you want peace, real relationships, and to feel safe with the people you love.",
        gifts: "You sense things before others, you create deep bonds, and you need beauty and harmony around you.",
        challenge: "To avoid conflict, you sometimes keep everything inside and build up anger. You might always put others before yourself.",
        example: "You're the one who feels others' pain as if it were your own. You create places where everyone feels at home.",
        advice: "True peace isn't avoiding problems, but facing them calmly. Learn to say what you feel.",
      },
      personalita: {
        synthesis: "People see you as a gentle, reliable person who puts others at ease.",
        gifts: "When you're around, people relax. You give the impression of being calm and trustworthy.",
        challenge: "Sometimes you seem too nice and someone might take advantage. You need to learn to say no.",
        example: "You're the one everyone tells their secrets to. They seek you out when they're hurting because they know you'll listen.",
        advice: "Show your strength too. Those who truly love you will also respect your boundaries.",
      },
      quintessenza: {
        synthesis: "You're at your best when you bring people together and create harmony around you.",
        gifts: "You know how to build bridges between different people and turn differences into richness.",
        challenge: "By helping everyone, you risk forgetting yourself. Finding your balance is the most important lesson.",
        example: "You're like someone who creates a group where different people understand and collaborate with each other.",
        advice: "You're the glue that holds things together. But remember: even glue needs care.",
      },
    },
    3: {
      destino: {
        synthesis: "The number of those who can communicate, create, and bring joy to others' lives.",
        gifts: "You have infectious enthusiasm, you speak well, you have talent for art and creativity, and you make friends easily.",
        challenge: "You risk starting a thousand things without finishing any. Sometimes you use humor to avoid facing serious problems.",
        example: "Think of an artist who can move people with their work. Or someone who explains difficult things in a simple and fun way.",
        advice: "Your creativity is like a river: without direction, it scatters. Choose one thing and dedicate yourself fully: the results will surprise you.",
      },
      io: {
        synthesis: "You express yourself with vitality and charisma. People listen to you willingly because you're a great communicator.",
        gifts: "You can tell stories, entertain, and make people laugh. You have natural creativity and people are drawn to your energy.",
        challenge: "Sometimes you seem unserious or scattered. You need to learn to add substance to what you say.",
        example: "You're the one who captures everyone's attention with a story. You turn every conversation into something interesting.",
        advice: "Words have enormous power: use them to help others grow, not just to entertain.",
      },
      anima: {
        synthesis: "Deep down, you want to express yourself, be unique, and enjoy the beauty of life.",
        gifts: "You have natural inner creativity, you're optimistic, you love beautiful things, and you find joy in small things.",
        challenge: "The need for others' approval can lead you to hide what you truly feel. Sometimes you use lightness to escape pain.",
        example: "You're the one who truly feels alive only when creating. You find poetry even in the simplest things.",
        advice: "You don't always have to be the life of the party. Rain is needed to grow flowers too: let difficult emotions pass through you.",
      },
      personalita: {
        synthesis: "People see you as a sunny, likeable person full of life.",
        gifts: "You bring good cheer wherever you go. You have the gift of lightening heavy situations and making people smile.",
        challenge: "Sometimes you seem unserious and people might not take your depth seriously.",
        example: "You're the one invited to every party because you create the right atmosphere. You bring light wherever you go.",
        advice: "Show your deeper side too. The best friendships are born when you show who you really are.",
      },
      quintessenza: {
        synthesis: "You're at your best when you communicate creatively and bring joy to people.",
        gifts: "You can turn ideas into something that touches people's hearts. Your creativity carries a powerful message.",
        challenge: "Too many ideas and too little discipline can block you. You need to choose what to focus on.",
        example: "You're like an artist who changes the way people see things, using beauty and words.",
        advice: "You have the gift of making things shine. Choose what to illuminate and dedicate all your energy to it.",
      },
    },
    4: {
      destino: {
        synthesis: "The number of those who build solid things, with patience and method.",
        gifts: "You're reliable, consistent, and concrete. You know how to build things that last, step by step.",
        challenge: "Sometimes you're too rigid and afraid of change. You cling to habits and struggle to accept new things.",
        example: "Think of someone building a house brick by brick. Or a parent creating a safe environment for their children. Someone building a business with patience and consistency.",
        advice: "The best foundations are those that can bend. A tree survives the storm because it's flexible, not because it's rigid.",
      },
      io: {
        synthesis: "You express yourself with order, precision, and organize things like no one else.",
        gifts: "You're reliable, you plan well, you care about details, and you express yourself clearly and concretely.",
        challenge: "Sometimes you seem too rigid or predictable. You need to make room for your spontaneous side.",
        example: "You're the one who transforms chaos into order effortlessly. Everyone seeks you when a precise plan is needed.",
        advice: "Order is your superpower, but let life surprise you once in a while. The unexpected can be beautiful too.",
      },
      anima: {
        synthesis: "Deep down, you want security, stability, and everything in its place.",
        gifts: "You have rare inner consistency, a strong sense of duty, and the patience to build things calmly.",
        challenge: "The need to control everything can block you. You might resist changes out of fear of the unknown.",
        example: "You're the one who finds peace when the job is done well. You feel at home when everything is in order.",
        advice: "True security doesn't come from external things. Learn to feel stable even when everything changes: that's where you truly grow.",
      },
      personalita: {
        synthesis: "People see you as a solid, serious person with their feet on the ground.",
        gifts: "You give stability to those around you. People trust you because you always seem prepared.",
        challenge: "Sometimes you seem boring or too serious. People might not see your creative and fun side.",
        example: "You're the one everyone entrusts with important things. You're always chosen for the most delicate tasks.",
        advice: "Surprise people once in a while. Show your playful side: they'll appreciate you even more.",
      },
      quintessenza: {
        synthesis: "You're at your best when you build something important that lasts over time.",
        gifts: "You can give concrete form to ideas and turn dreams into real, solid things.",
        challenge: "Wanting everything perfect can block you. Don't wait for everything to be in place before starting.",
        example: "You're like someone who builds things that endure and serve many people.",
        advice: "Build with love, not just with method. The things that last longest are those where you put your heart.",
      },
    },
    5: {
      destino: {
        synthesis: "The number of those who love change, freedom, and living many different experiences.",
        gifts: "You adapt to everything, you're curious, versatile, you have the courage to explore, and you reinvent yourself when needed.",
        challenge: "You risk being unstable and going to excess. You might flee responsibilities, always chasing something new.",
        example: "Think of someone who learns more from traveling than from books. Or someone who changes jobs to follow their passion. Someone who turns every problem into an opportunity.",
        advice: "True freedom isn't running away, but consciously choosing where to stay. Find your stability even in movement.",
      },
      io: {
        synthesis: "You express yourself with energy, always in motion, attracted to everything new.",
        gifts: "You adapt easily, communicate with vivacity, seize opportunities on the fly, and have contagious energy.",
        challenge: "Sometimes you seem inconsistent or unreliable. You need to learn to finish what you start.",
        example: "You're the one who feels at home everywhere. You turn every experience into a captivating story.",
        advice: "You can go deep even while standing still. Not everything that glitters is gold: choose carefully.",
      },
      anima: {
        synthesis: "Deep down, you want freedom, adventure, and the chance to try everything in life.",
        gifts: "You have a free spirit, a great thirst for experiences, an open mind, and you get excited about new things.",
        challenge: "Your need for freedom can prevent you from truly committing. You might run away right when things get serious.",
        example: "You're the one who feels suffocated by routine. You need to feel fresh air on your face to feel alive.",
        advice: "The greatest adventure is knowing yourself. You don't need to go far to find what you're looking for.",
      },
      personalita: {
        synthesis: "People see you as an energetic, fascinating person full of surprises.",
        gifts: "You have natural charm, you give an impression of freedom and adventure, and you attract people with your freshness.",
        challenge: "Sometimes you seem superficial or elusive. People might struggle to trust your consistency.",
        example: "You're the one everyone would want as a travel companion. You bring a breath of fresh air wherever you go.",
        advice: "Be fascinating but also reliable. People need to know they can count on you.",
      },
      quintessenza: {
        synthesis: "You're at your best when you bring positive changes and renew things.",
        gifts: "You know how to bring fresh air where it's needed and see possibilities where others see walls.",
        challenge: "Restlessness can ruin what you build. Learn to stay long enough to reap the rewards.",
        example: "You're like someone who can change an entire environment with their energy and desire for novelty.",
        advice: "The strongest change is the one born from awareness, not from escape.",
      },
    },
    6: {
      destino: {
        synthesis: "The number of those who take care of others, love family, and seek harmony in everything.",
        gifts: "You know how to protect and care for those you love, create beauty and harmony around you, and have a great sense of responsibility and an eye for beautiful things.",
        challenge: "You risk sacrificing too much for others and confusing love with control. You might feel guilty if you can't help everyone.",
        example: "Think of a parent who creates a safe environment without smothering. Or someone who dedicates their life to making the world a more beautiful and just place.",
        advice: "You can't pour from an empty cup. Take care of yourself with the same attention you give to others.",
      },
      io: {
        synthesis: "You express yourself with warmth and make people feel loved and protected.",
        gifts: "You create harmony, have artistic talent, express yourself with love, and have a beautiful aesthetic sense.",
        challenge: "Sometimes you seem too clingy or protective. You need to learn to love without controlling.",
        example: "You're the one who transforms every place into a welcoming space. Your presence makes everyone feel important.",
        advice: "The greatest love is the one that sets free. Love without taking away the freedom of those you care about.",
      },
      anima: {
        synthesis: "Deep down, you want love, beauty, and the chance to care for those around you.",
        gifts: "You love unconditionally, have a natural sense of beauty, create harmony, and dedicate yourself wholeheartedly.",
        challenge: "The need to feel necessary can create dependency. You might confuse sacrifice with love.",
        example: "You're the one who wants to make every detail beautiful. You light up when you can take care of someone.",
        advice: "Love yourself as you love others. The beauty you seek outside is already within you.",
      },
      personalita: {
        synthesis: "People see you as a warm, responsible person with good taste.",
        gifts: "When you're there, people feel safe. You give the impression of being reliable and caring.",
        challenge: "Sometimes you seem too protective. People might feel smothered by your attention.",
        example: "You're the one who organizes everything to make others comfortable. You're always chosen as a confidant.",
        advice: "Let others make their own mistakes. We grow through experience, not through protection.",
      },
      quintessenza: {
        synthesis: "You're at your best when you love consciously and create beauty around you.",
        gifts: "You transform environments and relationships through your love and care.",
        challenge: "Wanting everything perfect in relationships can prevent you from accepting life's imperfections.",
        example: "You're like someone who creates a community where people feel loved and respected.",
        advice: "Perfection doesn't exist, but beauty does. You find it in imperfections: that's where the magic is.",
      },
    },
    7: {
      destino: {
        synthesis: "The number of those who think deeply, seek answers, and want to understand the meaning of things.",
        gifts: "You can analyze, think deeply, have great intuition, and always seek the truth.",
        challenge: "You risk isolating yourself from the world and retreating into your head. You might become distrustful and struggle to trust others.",
        example: "Think of the researcher who dedicates their life to understanding how things work. Or the philosopher who asks questions no one else does. Someone who finds answers where others don't look.",
        advice: "The most beautiful thing you can do with what you know is share it. Don't be afraid to open up: wisdom grows when you give it away.",
      },
      io: {
        synthesis: "You express yourself with few words but full of meaning. You always get to the heart of things.",
        gifts: "You think deeply, see beyond appearances, and when you speak, you say things that truly matter.",
        challenge: "Sometimes you seem distant or superior. You need to learn to explain your ideas simply and accessibly.",
        example: "You're the one who hits the point with just two words. Everyone asks your opinion because you see things differently.",
        advice: "Not everything is understood with the mind. Sometimes make room for the heart and gut feelings.",
      },
      anima: {
        synthesis: "Deep down, you want to understand, seek the truth, and have moments of peace and silence.",
        gifts: "You have deep intuition, always seek meaning, know how to be in silence, and have a natural inner quest.",
        challenge: "The need to be alone can become isolation. You might use your mind as a shield to avoid feeling emotions.",
        example: "You're the one who needs silence to recharge. You find peace when you can think and reflect in tranquility.",
        advice: "The truth you seek isn't only in books. Sometimes the answer comes when you stop looking and let go.",
      },
      personalita: {
        synthesis: "People see you as a mysterious, intelligent person who knows many things.",
        gifts: "You have an interesting aura, people respect you, and they'd love to know what you really think.",
        challenge: "Sometimes you seem cold or impossible to approach. People might feel uncomfortable around you.",
        example: "You're the one whose thoughts everyone would love to know. You attract people with your depth and mystery.",
        advice: "Let yourself be known. People who deserve your time will appreciate your truth more than your mystery.",
      },
      quintessenza: {
        synthesis: "You're at your best when you seek the truth and share it with others.",
        gifts: "You can go deep into things and transform what you learn into useful advice for everyone.",
        challenge: "Thinking too much can block you. Sometimes you need to act before understanding everything.",
        example: "You're like the teacher who transforms their research into simple teachings that change people's lives.",
        advice: "The greatest wisdom is knowing you don't know everything. Stay curious and humble: truth reveals itself to those who are open.",
      },
    },
    8: {
      destino: {
        synthesis: "The number of those who know how to manage power, money, and resources with strength and vision.",
        gifts: "You can lead people, have a nose for business, are determined, and have a clear vision of where you want to go.",
        challenge: "You risk thinking only about money and success, becoming harsh with others. You might use power to control rather than to help.",
        example: "Think of someone who builds a successful business with integrity. Or someone who uses their resources for the good of the community. Someone who creates wealth for themselves and others.",
        advice: "True power isn't what you use over others, but what you use on yourself. Use what you have honestly and success will last forever.",
      },
      io: {
        synthesis: "You express yourself with authority and ambition. You manage people and situations with confidence.",
        gifts: "You have a clear vision, organize well, project strength and competence, and have a natural talent for managing things.",
        challenge: "Sometimes you seem too ambitious or calculating. You need to show your human and gentle side too.",
        example: "You're the one who turns every situation into an opportunity. You see potential where others see problems.",
        advice: "Success without meaning is empty. Always ask yourself: for whom and for what am I working?",
      },
      anima: {
        synthesis: "Deep down, you want abundance, recognition, and to leave a mark on the world.",
        gifts: "You have healthy ambition, a strong sense of justice, want to do excellent things, and have enormous inner strength.",
        challenge: "The need for success can make you dependent on others' judgment. You might confuse your worth with your achievements.",
        example: "You're the one who feels born to do something great. You never settle for mediocrity.",
        advice: "You are not your results. Your worth doesn't depend on what you possess or achieve. You matter for who you are.",
      },
      personalita: {
        synthesis: "People see you as a powerful, ambitious person capable of great things.",
        gifts: "You have a strong presence, project success and competence, and people trust your abilities.",
        challenge: "Sometimes you're a bit intimidating. People might fear not being up to your expectations.",
        example: "You're the one everyone would want as a partner. You project an energy of determination and success.",
        advice: "Show your generosity too. The strongest people are those who use their power to help others.",
      },
      quintessenza: {
        synthesis: "You're at your best when you create abundance honestly and generously.",
        gifts: "You can turn ideas into concrete things and create wealth that benefits everyone.",
        challenge: "The temptation to use power only for yourself is your greatest test. You need to find the balance between having and giving.",
        example: "You're like someone who builds businesses that create value for people, not just profit.",
        advice: "The greatest power is doing good on a large scale. Use your abilities to serve, not just to accumulate.",
      },
    },
    9: {
      destino: {
        synthesis: "The number of those with a big heart, who understand others' pain and want to leave the world a better place.",
        gifts: "You know how to forgive, see things from above, have wisdom from experience, and give without expecting anything in return.",
        challenge: "You risk carrying everyone's problems on your shoulders. You might play the victim or waste your energy trying to fix everything without caring for yourself.",
        example: "Think of a doctor who goes to heal people in war zones. Or a grandparent who teaches grandchildren values that last forever. Someone who forgives even when it's hard, because they understand we're all fragile.",
        advice: "You can't save the world if you're not well first. Learn to let go of things you can't change: true wisdom is knowing what's worth keeping.",
      },
      io: {
        synthesis: "You express yourself with humanity and generosity. You have a natural calling to help others.",
        gifts: "You see the big picture, inspire compassion, and have the talent to make people feel understood and welcomed.",
        challenge: "Sometimes you seem detached or too idealistic. You need to stay grounded even when you dream big.",
        example: "You're the one who touches people's hearts with words and actions. You inspire others to become better people.",
        advice: "You don't have to be perfect to make a difference. Even a small act of kindness can change someone's day.",
      },
      anima: {
        synthesis: "Deep down, you want to do something good for the world and help humanity grow.",
        gifts: "You have deep compassion, soul wisdom, know how to forgive, and love people universally.",
        challenge: "The need to save others can make you forget yourself. You might feel responsible for everyone's pain.",
        example: "You're the one who feels a deep connection with all of humanity. You cry for injustices even when they don't involve you.",
        advice: "Helping doesn't mean sacrificing yourself. You do more good in the world when you're balanced and well yourself first.",
      },
      personalita: {
        synthesis: "People see you as a wise person with a big heart who understands everyone.",
        gifts: "You have a warm presence, people feel welcomed by you, and you give the impression of being a deep and understanding person.",
        challenge: "Sometimes you seem too distant or in another world. People might see you as unreachable.",
        example: "You're the one everyone respects for their honesty. They seek you because you understand without judging.",
        advice: "Be present in everyday life, not just in big ideas. People need your humanity, not your perfection.",
      },
      quintessenza: {
        synthesis: "You're at your best when you help others with awareness and transform pain into wisdom.",
        gifts: "You can find deep meaning in every experience and guide others through moments of change.",
        challenge: "The risk is dreaming big without doing anything concrete. Wisdom without action serves no one.",
        example: "You're like the teacher who has been through life's difficulties and drawn out lessons to share with everyone.",
        advice: "Your wisdom is your most precious gift. Don't keep it to yourself: the world needs your light.",
      },
    },
    11: {
      destino: {
        synthesis: "The master number of those with a special vision, extraordinary intuition, and very strong sensitivity.",
        gifts: "You have an incredibly strong sixth sense, you inspire others, you're very sensitive, and you see things that other people don't.",
        challenge: "You live in tension between the practical world and the inner world. You may suffer from anxiety, feel too sensitive, and think you're not up to your mission.",
        example: "Think of someone who sees things before others and knows where the future is heading. Or an artist who creates works that seem to come from another world. Someone who awakens people's consciousness.",
        advice: "You don't have to carry this weight alone. Your gift is like a channel: let the light pass through, don't hold it back. Keep your feet on the ground while looking at the sky: your vision needs solid foundations.",
      },
      io: {
        synthesis: "You express yourself as a source of inspiration, with special sensitivity and intuition.",
        gifts: "You inspire people deeply, your intuition guides everything you do, and you have an extraordinary artistic sensitivity.",
        challenge: "Being so sensitive can make you suffer. The challenge is expressing your vision without being overwhelmed.",
        example: "You're the one whose words or gestures touch deep chords in people. Your work seems to come from a special source.",
        advice: "You're a lighthouse: your light guides others. But remember to rest and take care of your flame.",
      },
      anima: {
        synthesis: "Deep inside, you're guided by a greater vision and the need to illuminate others' path.",
        gifts: "You have almost magical intuition, rare sensitivity, a connection to something greater, and the ability to sense invisible things.",
        challenge: "Your extreme sensitivity can make you fragile in front of others' energy. You might feel like a fish out of water in this world.",
        example: "You're the one who perceives things others can't see. You have dreams that come true or intuitions that always prove right.",
        advice: "Your gift is real, you're not strange. Learn to protect your energy and choose whom to share what you see with.",
      },
      personalita: {
        synthesis: "People see you as a special, intense person with a particular light.",
        gifts: "You have a magnetic presence, you inspire people, and you give the impression of unique depth and sensitivity.",
        challenge: "Sometimes you seem too intense or different. People might not understand your depth.",
        example: "You're the one who changes the atmosphere when entering a room. You inspire others simply with your presence.",
        advice: "Not everyone will understand your light, and that's okay. Surround yourself with people who see your value.",
      },
      quintessenza: {
        synthesis: "You're at your best when you illuminate others with your vision and intuition.",
        gifts: "You can transform inspiration into something concrete and useful, and you have the talent of awakening people's hidden potential.",
        challenge: "The tension between what you see and reality can tire you. Find a way to bring your intuitions into the real world.",
        example: "You're like the visionary teacher who transforms intuitions into simple teachings that change people's lives.",
        advice: "Your vision is a gift to the world. Don't let it die in indecision: act with courage.",
      },
    },
    22: {
      destino: {
        synthesis: "The master number of the great builder: someone capable of creating enormous projects that last over time.",
        gifts: "You have a grand vision, you can turn big ideas into concrete things, you're a transformative leader, and you unite dreams with practice.",
        challenge: "You feel enormous pressure, from yourself and from others. You might collapse under expectations or live small out of fear of your own greatness.",
        example: "Think of someone who founds an organization that changes the rules of the game. Or someone who creates systems that improve many people's lives. Someone who builds bridges between the impossible and the possible.",
        advice: "You were born to build something great, but you don't have to do it all at once. Every cathedral was built one stone at a time. Start, and the project will take shape on its own.",
      },
      io: {
        synthesis: "You express yourself as a builder of visions: you can turn the impossible into reality.",
        gifts: "You see the complete project in your mind and build it step by step. You unite dream with practice.",
        challenge: "The grandeur of your vision can paralyze you. The challenge is starting even when the goal seems impossible.",
        example: "You're the one who presents a huge idea so concretely that everyone wants to be part of it.",
        advice: "Don't underestimate the power of the first step. Every great work begins with a single act of courage.",
      },
      anima: {
        synthesis: "Deep down, you want to leave something concrete that lasts longer than you.",
        gifts: "You think long-term, think big, and have the determination to build something that serves everyone's good.",
        challenge: "The weight of your mission can crush you. You might feel not up to what you're called to do.",
        example: "You're the one who feels they have a mission greater than themselves. You can't settle for an ordinary life.",
        advice: "You don't have to be perfect to start. The world needs your imperfect constructions more than your standing perfection.",
      },
      personalita: {
        synthesis: "People see you as a visionary yet concrete person, capable of great things.",
        gifts: "You have an authoritative presence, give the impression of being competent and visionary, and people trust your big projects.",
        challenge: "Sometimes you seem too ambitious or distant. People might feel small next to you.",
        example: "You're the one who, when talking about a project, makes everyone believe it's possible. You inspire trust even in the most difficult ventures.",
        advice: "Involve others in your vision. Great builders don't build alone: they know how to inspire and get everyone working together.",
      },
      quintessenza: {
        synthesis: "You're at your best when you create concrete things that serve many people.",
        gifts: "You have a unique talent for turning dreams into real things and building things that last for future generations.",
        challenge: "Perfection is the enemy of good. Don't wait for ideal conditions: build with what you have.",
        example: "You're like someone who creates organizations, systems, or works that change the rules for those who come after.",
        advice: "You're the bridge between heaven and earth. Your mission is to make concrete what others can only dream of.",
      },
    },
    33: {
      destino: {
        synthesis: "The master number of universal love: a loving guide who dedicates their life to others.",
        gifts: "You love unconditionally, heal others' wounds, guide with gentleness, dedicate yourself to service, and inspire people at a deep level.",
        challenge: "You risk sacrificing yourself completely for others, forgetting that you too need to be cared for. You might lose yourself trying to help everyone.",
        example: "Think of the teacher who dedicates their life to helping others grow. Or someone who gives up their own interests for a greater good. The person who becomes a reference point for an entire community.",
        advice: "Love for all begins with love for yourself. You can't illuminate the world if your light has gone out. Take care of yourself with the same gentleness you give others.",
      },
      io: {
        synthesis: "You express yourself as a loving guide who inspires change through kindness.",
        gifts: "You heal with your mere presence, express a love that goes beyond the personal, and guide people with gentleness.",
        challenge: "Sacrificing too much can consume you. The challenge is serving others without losing yourself.",
        example: "You're the one whose presence alone brings peace and healing. Your love transforms those around you.",
        advice: "Help with joy, not with sacrifice. Love given out of obligation is not love, it's a chain.",
      },
      anima: {
        synthesis: "Deep down, you want to love and serve people with everything you have.",
        gifts: "You have immense love, limitless compassion, and the ability to see beauty in every person.",
        challenge: "You might completely lose yourself for others. The line between dedication and sacrifice is thin.",
        example: "You're the one who feels the world's pain as if it were your own. You can't turn your back on anyone.",
        advice: "Even great teachers need to rest. Your love is stronger when it comes from a full heart, not an empty one.",
      },
      personalita: {
        synthesis: "People see you as a luminous person, full of love and who inspires everyone.",
        gifts: "Your presence heals, you give the impression of being wise and full of compassion, and you make everyone feel loved.",
        challenge: "Sometimes you seem too good or naive. Someone might take advantage of your generosity.",
        example: "You're the one whose presence brings peace to every room. You inspire others to become kinder.",
        advice: "Your goodness is not weakness. But learn to recognize who truly deserves your energy.",
      },
      quintessenza: {
        synthesis: "You're at your best when your love transforms things and you guide others with your heart.",
        gifts: "You can transform suffering into wisdom and love into a force that heals everyone.",
        challenge: "The weight of wanting to help everyone can crush you. You're not responsible for saving every person.",
        example: "You're like the healer-teacher whose life becomes an example of unconditional love.",
        advice: "You're a light in the world. But even light needs to be fueled. Take care of your flame.",
      },
    },
  },
};

// Cycle-specific descriptions per number
const cycleDescriptions: Record<Lang, Record<number, NumberTemplateDesc>> = {
  it: {
    1: {
      synthesis: "Un periodo di nuovi inizi: è il momento di fare le cose a modo tuo e prendere il comando.",
      gifts: "Coraggio di iniziare cose nuove, saper stare in piedi da solo, prendere decisioni importanti senza aspettare gli altri.",
      challenge: "Rischi di isolarti o di voler fare tutto da solo. L'egoismo può allontanare le persone che ami.",
      example: "Pensa al periodo in cui cambi lavoro, ti trasferisci o inizi un progetto tutto tuo. Il momento in cui smetti di aspettare il permesso degli altri.",
      advice: "Questo periodo ti chiede di osare. Non aver paura di stare da solo: è nella solitudine giusta che trovi la tua vera forza.",
    },
    2: {
      synthesis: "Un periodo in cui le relazioni contano più di tutto. È il momento di collaborare e avere pazienza.",
      gifts: "Sensibilità verso gli altri, capacità di mettere d'accordo le persone, empatia, saper creare legami veri.",
      challenge: "Potresti diventare troppo dipendente dagli altri o evitare i litigi a tutti i costi, perdendoti nel processo.",
      example: "Pensa al periodo dei matrimoni, delle amicizie profonde, delle collaborazioni importanti che ti cambiano la vita.",
      advice: "Questo periodo ti insegna che la vera forza è nel lavoro di squadra. Impara ad ascoltare, ma non dimenticare la tua voce.",
    },
    3: {
      synthesis: "Un periodo di creatività e comunicazione. È il momento di esprimerti e goderti la vita.",
      gifts: "La creatività fiorisce, sai comunicare meglio che mai, sei socievole e il tuo entusiasmo è contagioso.",
      challenge: "Iniziare mille cose senza finirne nessuna. Troppi stimoli e poca costanza possono bloccarti.",
      example: "Pensa al periodo in cui scopri un talento, inizi a scrivere, dipingere, cantare o ti dedichi a qualcosa che ti rappresenta.",
      advice: "Esprimi quello che senti senza paura. Ma ricorda: la creatività senza costanza resta un sogno nel cassetto.",
    },
    4: {
      synthesis: "Un periodo di costruzione e impegno. È il momento di mettere le basi per qualcosa di solido.",
      gifts: "Costanza, saper organizzare le cose, essere concreto, avere la forza di costruire qualcosa che dura.",
      challenge: "Essere troppo rigido e aver paura dei cambiamenti. Potresti sentirti intrappolato nella routine.",
      example: "Pensa al periodo in cui compri casa, stabilisci la carriera, crei una famiglia stabile o costruisci qualcosa di importante mattone dopo mattone.",
      advice: "Questo periodo richiede pazienza e lavoro costante. Non cercare scorciatoie: quello che costruisci adesso durerà a lungo.",
    },
    5: {
      synthesis: "Un periodo di cambiamento e libertà. Tutto si muove e niente resta uguale.",
      gifts: "Saper adattarsi, coraggio di cambiare, apertura al nuovo, capacità di reinventarsi, tanta energia.",
      challenge: "L'instabilità e la voglia di scappare possono portarti a evitare le responsabilità. Rischi di esagerare con gli eccessi.",
      example: "Pensa ai periodi dei viaggi, dei cambiamenti di lavoro, delle relazioni inaspettate. Tutto si muove e cambia in continuazione.",
      advice: "Abbraccia il cambiamento ma tieni un centro dentro di te. La vera libertà non è scappare, è scegliere con consapevolezza.",
    },
    6: {
      synthesis: "Un periodo dedicato alla famiglia, all'amore e alla cura delle persone che ami.",
      gifts: "Saper prenderti cura degli altri, senso della bellezza, dedizione alla famiglia, creare ambienti belli e accoglienti.",
      challenge: "Sacrificarti troppo e voler controllare tutto può esaurirti. Rischi di dimenticarti completamente di te stesso.",
      example: "Pensa al periodo in cui ti dedichi ai figli, alla famiglia, alla casa. Le relazioni diventano il centro di tutto.",
      advice: "Ama senza perdere te stesso. La cura più importante è quella che dai a te: solo da lì nasce un amore che dura.",
    },
    7: {
      synthesis: "Un periodo di riflessione e crescita interiore. È il momento di rallentare e guardarti dentro.",
      gifts: "Pensiero profondo, intuizione forte, voglia di capire, saggezza che nasce dal fermarsi a riflettere.",
      challenge: "Isolarti troppo e non fidarti di nessuno. Potresti pensare troppo e sentire troppo poco.",
      example: "Pensa al periodo in cui ti ritiri per studiare, meditare, fare terapia o iniziare un cammino di crescita personale.",
      advice: "Questo periodo ti chiede di rallentare e guardare dentro di te. Le risposte che cerchi non sono fuori, sono nel silenzio.",
    },
    8: {
      synthesis: "Un periodo di risultati concreti e successo. È il momento di raccogliere quello che hai seminato.",
      gifts: "Saper gestire le cose, fiuto per gli affari, forza di volontà, determinazione nel raggiungere i tuoi obiettivi.",
      challenge: "Pensare solo ai soldi e al successo può allontanarti dalle persone. Il potere senza cuore fa danni.",
      example: "Pensa al periodo delle promozioni, del successo economico, dei riconoscimenti nel lavoro. È il momento di raccogliere i frutti.",
      advice: "Usa il potere che questo periodo ti dà con saggezza. Il vero successo è quello che fa stare bene anche chi ti sta intorno.",
    },
    9: {
      synthesis: "Un periodo di chiusura e trasformazione. È il momento di lasciar andare e prepararsi a ricominciare.",
      gifts: "Compassione, visione ampia, saper lasciar andare le cose, saggezza che viene dall'esperienza.",
      challenge: "Aggrapparti al passato può impedirti di andare avanti. La nostalgia e il lamentarsi possono bloccarti.",
      example: "Pensa al periodo in cui chiudi relazioni, lavori o fasi della vita che hanno fatto il loro tempo. Fai i conti con il passato e ti prepari al nuovo.",
      advice: "Lascia andare con gratitudine. Ogni fine è un nuovo inizio nascosto. Le cose che sono davvero tue torneranno sempre.",
    },
    11: {
      synthesis: "Un periodo di risveglio interiore, con intuizioni forti e una sensibilità fuori dal comune.",
      gifts: "Intuizione fortissima, sensibilità elevata, capacità di ispirare, connessione con qualcosa di più grande.",
      challenge: "Essere troppo sensibile e teso può renderti fragile. Il peso di quello che senti può sembrare troppo.",
      example: "Pensa al periodo delle rivelazioni interiori, delle coincidenze frequenti, dei sogni significativi. Senti che qualcosa di più grande ti guida.",
      advice: "Non resistere a quello che senti: è il tuo dono. Tieni i piedi per terra con le abitudini quotidiane per sostenere l'intensità di questo periodo.",
    },
    22: {
      synthesis: "Un periodo per costruire qualcosa di grande che avrà un impatto su tante persone.",
      gifts: "Saper realizzare cose che sembrano impossibili, guidare con visione, unire sogni e pratica in modo unico.",
      challenge: "La pressione delle aspettative può schiacciarti. Potresti vivere in piccolo per paura della tua stessa grandezza.",
      example: "Pensa al periodo in cui un progetto importante della tua vita prende forma e ha un impatto che va ben oltre te.",
      advice: "Sei chiamato a costruire qualcosa di grande. Non farti spaventare dalle dimensioni: vai avanti un passo alla volta.",
    },
    33: {
      synthesis: "Un periodo dedicato ad aiutare gli altri con amore e a diventare una guida per chi ti circonda.",
      gifts: "Amore senza condizioni, capacità di curare, guida gentile, ispirazione per le persone intorno a te.",
      challenge: "Sacrificarti troppo e dimenticarti completamente di te. Rischi di dare tutto senza lasciare niente per te.",
      example: "Pensa al periodo in cui diventi un punto di riferimento per gli altri, un maestro, una guida. La gente cerca la tua luce.",
      advice: "Aiuta con amore, ma non dimenticarti di te stesso. La tua luce ha bisogno di essere alimentata.",
    },
  },
  en: {
    1: {
      synthesis: "A period of new beginnings: it's time to do things your way and take charge.",
      gifts: "Courage to start new things, ability to stand on your own, making important decisions without waiting for others.",
      challenge: "You risk isolating yourself or wanting to do everything alone. Selfishness can push away the people you love.",
      example: "Think of a time when you change jobs, move, or start a project of your own. The moment you stop waiting for others' permission.",
      advice: "This period asks you to dare. Don't be afraid of being alone: it's in the right solitude that you find your true strength.",
    },
    2: {
      synthesis: "A period where relationships matter more than anything. It's time to collaborate and be patient.",
      gifts: "Sensitivity toward others, ability to bring people together, empathy, creating genuine bonds.",
      challenge: "You might become too dependent on others or avoid conflicts at all costs, losing yourself in the process.",
      example: "Think of a time of marriages, deep friendships, important collaborations that change your life.",
      advice: "This period teaches you that true strength is in teamwork. Learn to listen, but don't forget your own voice.",
    },
    3: {
      synthesis: "A period of creativity and communication. It's time to express yourself and enjoy life.",
      gifts: "Creativity blooms, you communicate better than ever, you're sociable, and your enthusiasm is contagious.",
      challenge: "Starting a thousand things without finishing any. Too many stimuli and too little consistency can block you.",
      example: "Think of a time when you discover a talent, start writing, painting, singing, or dedicate yourself to something that represents you.",
      advice: "Express what you feel without fear. But remember: creativity without consistency remains a dream in a drawer.",
    },
    4: {
      synthesis: "A period of building and commitment. It's time to lay the foundation for something solid.",
      gifts: "Consistency, ability to organize, being concrete, having the strength to build something that lasts.",
      challenge: "Being too rigid and fearing change. You might feel trapped in routine.",
      example: "Think of a time when you buy a house, establish your career, create a stable family, or build something important brick by brick.",
      advice: "This period requires patience and steady work. Don't look for shortcuts: what you build now will last a long time.",
    },
    5: {
      synthesis: "A period of change and freedom. Everything moves and nothing stays the same.",
      gifts: "Adaptability, courage to change, openness to the new, ability to reinvent yourself, lots of energy.",
      challenge: "Instability and the urge to run can lead you to avoid responsibilities. You risk going to excess.",
      example: "Think of times of travel, job changes, unexpected relationships. Everything moves and changes constantly.",
      advice: "Embrace change but keep a center within yourself. True freedom isn't running away, it's choosing with awareness.",
    },
    6: {
      synthesis: "A period dedicated to family, love, and caring for the people you love.",
      gifts: "Knowing how to care for others, sense of beauty, dedication to family, creating beautiful and welcoming environments.",
      challenge: "Sacrificing too much and wanting to control everything can drain you. You risk completely forgetting yourself.",
      example: "Think of a time when you dedicate yourself to children, family, home. Relationships become the center of everything.",
      advice: "Love without losing yourself. The most important care is what you give to yourself: only from there does lasting love arise.",
    },
    7: {
      synthesis: "A period of reflection and inner growth. It's time to slow down and look within.",
      gifts: "Deep thinking, strong intuition, desire to understand, wisdom born from stopping to reflect.",
      challenge: "Isolating too much and not trusting anyone. You might think too much and feel too little.",
      example: "Think of a time when you retreat to study, meditate, go to therapy, or start a personal growth journey.",
      advice: "This period asks you to slow down and look inside. The answers you seek aren't outside, they're in the silence.",
    },
    8: {
      synthesis: "A period of concrete results and success. It's time to harvest what you've sown.",
      gifts: "Ability to manage things, nose for business, willpower, determination to achieve your goals.",
      challenge: "Thinking only about money and success can distance you from people. Power without heart causes damage.",
      example: "Think of a time of promotions, financial success, recognition at work. It's time to reap the rewards.",
      advice: "Use the power this period gives you wisely. True success is what also makes those around you feel good.",
    },
    9: {
      synthesis: "A period of closure and transformation. It's time to let go and prepare to start anew.",
      gifts: "Compassion, broad vision, ability to let things go, wisdom from experience.",
      challenge: "Clinging to the past can prevent you from moving forward. Nostalgia and complaining can block you.",
      example: "Think of a time when you close relationships, jobs, or life phases that have run their course. You settle with the past and prepare for the new.",
      advice: "Let go with gratitude. Every ending is a hidden new beginning. The things that are truly yours will always return.",
    },
    11: {
      synthesis: "A period of inner awakening, with strong intuitions and extraordinary sensitivity.",
      gifts: "Very strong intuition, elevated sensitivity, ability to inspire, connection with something greater.",
      challenge: "Being too sensitive and tense can make you fragile. The weight of what you feel can seem like too much.",
      example: "Think of a time of inner revelations, frequent coincidences, significant dreams. You feel something greater is guiding you.",
      advice: "Don't resist what you feel: it's your gift. Keep your feet on the ground with daily habits to support this period's intensity.",
    },
    22: {
      synthesis: "A period to build something great that will impact many people.",
      gifts: "Ability to accomplish things that seem impossible, leading with vision, uniquely uniting dreams and practice.",
      challenge: "The pressure of expectations can crush you. You might live small out of fear of your own greatness.",
      example: "Think of a time when an important project in your life takes shape and has an impact far beyond yourself.",
      advice: "You're called to build something great. Don't be scared by its size: move forward one step at a time.",
    },
    33: {
      synthesis: "A period dedicated to helping others with love and becoming a guide for those around you.",
      gifts: "Unconditional love, ability to heal, gentle guidance, inspiration for the people around you.",
      challenge: "Sacrificing too much and completely forgetting yourself. You risk giving everything without leaving anything for yourself.",
      example: "Think of a time when you become a reference point for others, a teacher, a guide. People seek your light.",
      advice: "Help with love, but don't forget yourself. Your light needs to be fueled.",
    },
  },
};

export function getNumberTemplate(num: number, type: NumberType, lang: string = 'it'): NumberTemplateDesc | null {
  const l = (lang?.substring(0, 2) === 'en' ? 'en' : 'it') as Lang;
  const baseNum = num > 9 && ![11, 22, 33].includes(num) ? num % 9 || 9 : num;
  if (type === 'ciclo') {
    return cycleDescriptions[l][baseNum] || null;
  }
  return templateDescriptions[l][baseNum]?.[type] || null;
}
